import { NextResponse } from 'next/server';

export async function POST(request: Request) {
  try {
    const { messages, experienceLevel } = await request.json();

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: 'Gemini API key is not configured on the server. Please add GEMINI_API_KEY to your environment variables.' },
        { status: 500 }
      );
    }

    // Adapt system prompt to user's financial experience level
    let toneGuide = '';
    if (experienceLevel === 'Beginner') {
      toneGuide = `
- The user is a BEGINNER. Use extremely simple everyday language.
- Avoid scary financial jargon. If you must use a term, explain it immediately.
- Use fun Nigerian business analogies (e.g., buying market shares like co-owning a shop in Balogun/Alaba market, dividing profits, etc.).`;
    } else if (experienceLevel === 'Intermediate') {
      toneGuide = `
- The user is INTERMEDIATE. You can use standard financial terms (P/E ratio, dividend yield, etc.) but briefly explain what they mean in context.
- Bridge basic concepts to analytical insights.`;
    } else {
      toneGuide = `
- The user is EXPERIENCED. Use professional, institutional-grade financial terminology directly.
- Focus on key metrics, valuation methodologies, market sentiment, and corporate actions.`;
    }

    const systemPrompt = `You are the EquityStack AI Assistant — a friendly, institutional-grade advisor specialized in the Nigerian stock market (NGX) and wealth building.

CRITICAL INSTRUCTIONS:
1. TOPIC GUARD: You MUST ONLY answer questions related to the Nigerian stock market (NGX), stocks, company analysis, personal finance, investing, economy, or closely related topics. If the user asks about other topics (e.g., coding, general history, writing fiction, cooking), politely decline and say: "I am trained to assist only with stock market investing and financial insights. Let's get back to your wealth journey! What stock or market concept would you like to explore?"
2. TONE & EXPERIENCE LEVEL:${toneGuide}
3. Maintain a helpful, objective, and encouraging tone.
4. Keep responses highly readable, using bullet points, short paragraphs, and formatting where appropriate.
5. REQUIRED DISCLAIMER: You MUST always end your response with this exact disclaimer block on a new line:
*Disclaimer: This information is generated by the EquityStack AI assistant for educational purposes only and should not be taken as professional financial or investment advice.*`;

    // Map history to Gemini's role format: 'user' and 'model'
    const formattedContents = messages.map((m: any) => {
      return {
        role: m.sender === 'user' ? 'user' : 'model',
        parts: [{ text: m.text }]
      };
    });

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: formattedContents,
          systemInstruction: {
            parts: [{ text: systemPrompt }]
          },
          generationConfig: {
            temperature: 0.3,
            maxOutputTokens: 800,
          }
        })
      }
    );

    if (!response.ok) {
      const errText = await response.text();
      console.error('Gemini API Error Response:', errText);
      return NextResponse.json(
        { error: `Gemini API returned error: ${response.status} ${response.statusText}` },
        { status: 502 }
      );
    }

    const data = await response.json();
    const replyText = data.candidates?.[0]?.content?.parts?.[0]?.text || 'No response generated.';

    return NextResponse.json({ reply: replyText });
  } catch (error: any) {
    console.error('API Error in /api/ai/chat:', error);
    return NextResponse.json(
      { error: error.message || 'Internal Server Error' },
      { status: 500 }
    );
  }
}
